// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGVMMQNqJDjCFTcUVdt-HO9g60F6jSxAQ',
    appId: '1:691730213458:android:3a520f277585e124790d8b',
    messagingSenderId: '691730213458',
    projectId: 'share-the-good',
    storageBucket: 'share-the-good.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-XNlD7BVd0FCu6y6TijeeGYfzQ8TXZkY',
    appId: '1:691730213458:ios:9dfef02f3994ad3c790d8b',
    messagingSenderId: '691730213458',
    projectId: 'share-the-good',
    storageBucket: 'share-the-good.appspot.com',
    androidClientId: '691730213458-bcgd32s0rp84jtqh94mqsvf95rb847mf.apps.googleusercontent.com',
    iosClientId: '691730213458-5vueksk1b4d18k9pflfudns7g3uvmov7.apps.googleusercontent.com',
    iosBundleId: 'com.sharethegood.sharethegood',
  );
}
